### ISSUE TITLE
Rechnungen auslesen

### ISSUE THREAD

**Issue by tdrzewosz** [FubarDevelopment/Lexware#3]
Hallo, das ist echt ein super Projekt. Wie komme ich bspw an die Rechnungen eines Kunden ran?

Danke

Gruß

**Comment by fubar-coder** [comment]
@tdrzewosz Ich habe keine Lexware-Lizenz mehr zur Verfügung und es hat sich beim Datenbank-Schema einiges getan, so dass dieses Projekt nur noch Dokumentations-Charakter hat.
